const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
const CLEAR_ERROR = "CLEAR_ERROR";

module.exports = {
  ALL_PRODUCT_REQUEST,
  ALL_PRODUCT_SUCCESS,
  ALL_PRODUCT_FAIL,
  CLEAR_ERROR,
};
